version: '3.8'

services:
  proyectoisma:
    image: proyectoisma:1
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    networks:
      - proyectoisma_net

  ismamongodb: 
    image: mongo:8.0
    environment:
      - MONGO_INITDB_DATABASE=integrador
    volumes:
      - mongodb_data:/data/db
    networks:
      - proyectoisma_net

volumes:
  mongodb_data:
    external: true

networks:
  proyectoisma_net:
    external: true
    driver: overlay
